# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Localization' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'FirebaseRemoteConfig'
pod 'RealmSwift'
# For Analytics without IDFA collection capability, use this pod instead
# pod ‘Firebase/AnalyticsWithoutAdIdSupport’

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore


  # Pods for Localization

  target 'LocalizationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LocalizationUITests' do
    # Pods for testing
  end

end
